#Welcome to the configuration file of UHCPLus!

#Set the active Presets configuration. Default: "default"
#Do not include the file extension!
defaultPreset: "default"

#List of available config files
availablePresets:
- "default"