#Welcome to the preset configuration file of UHCPLus!

#Set the maximum amount of teams. Range: 1-16, default: 16
maxTeamCount: "16"

#Set the maximum amount of players per team. Range: 1-infinite. Default: 4.
#If there are more players than that can be fit into teams, they will become spectators!
maxPlayerCountPerTeam: "4"

#Enable or disable the auto smelting of ores when a player mines them. Applies to gold, iron, emerald and coal ore. Coal ore will drop torches.
moduleOreAutoSmelt: "true"

#How many ingots should the mined ore drop
#For this to work moduleOreAutoSmelt needs to be enabled!
moduleOreAutoSmeltIngotDrop: "1"