name: UHCPlus
main: nl.thedutchmc.uhcplus.UhcPlus
version: 1.0.0
author: [TheDutchMC, TimeMaster111]
api-version: 1.15
description: TBD
commands:
 uhcp:
  description: uhcp base command. See /uhcp help for help.