#Welcome to the configuration file of UHCPLus!

#Set the active Presets configuration. Default: "default"
#Do not include the file extension!
defaultPreset: "default"

#List of available config files
availablePresets:
- "default"

#Do we only allow the UHC world to be a specified List of seeds. Default: true
onlyAllowedSeeds: "true"

#Allowed seeds, for this list to be used, onlyAllowedSeeds needs to be true!
#NUMERICAL SEEDS ONLY! NO ALPHABETIC SEEDS!
allowedSeeds:
- "-4088290688367012214"

#Can spectators run commands, operators are excluded. Default: false
spectatorsCanRunCommand: "false"

#Can spectators whisper to players who are still playing, operators are excluded. Default: false
#Is overriden by spectatorsCanRunCommand
spectatorCanWhisperToPlayer: "false"

#Do we enfore limited crafting of stone and wooden weapons and tools. Default: true
limitCrafting: "true"

#How many tools/weapons may be crafted. Default: 4
limitCraftingAmount: "4"

#Should the server restart after the UHC has ended. Default: true
restartAfterUhc: "true"

#How many seconds after the UHC should the server restart. Default: 180
timeUntilRestart: "180"
