#Welcome to the preset configuration file of UHCPLus!

#Set the maximum amount of teams. Range: 1-16, default: 16
maxTeamCount: "16"

#Set the maximum amount of players per team. Range: 1-infinite. Default: 4.
#If there are more players than that can be fit into teams, they will become spectators!
maxPlayerCountPerTeam: "4"

#Enable or disable the auto smelting of ores when a player mines them. Applies to gold, iron, emerald and coal ore. Coal ore will drop torches.
moduleOreAutoSmelt: "true"

#How many ingots should the mined ore drop
#For this to work moduleOreAutoSmelt needs to be enabled!
moduleOreAutoSmeltIngotDrop: "1"

#Time until PVP will be enabled, in minutes. Default: 5
timeToPvp: "5"

#The size of the world border at game start, in side length, For example: 1400 means the border will be at coordinate 700. Default: 1400
worldBorderSize: "1400"

#Time until the world border starts shrinking. Default: 0
worldBorderShrinkAfter: "0"

#The size of the world border after it has stopped shrinking, in side length. Default: 40
worldBorderShrinkTo: "40"

#Game time in minutes, default 60
gameTime: "60"

#Chop down trees when one block of the tree is broken. Can be true/false. Default: true
moduleTreeFullRemove: "true"

#Should leaves decay fast. Default: true
moduleLeaveDecay: "true"

#Should all tools get the enchants Efficiency 4 and Unbreaking 2. Default: true
moduleEnchantedTools: "true"

#Should player get a stack of enchanting tables, lapis blocks, anvils and the maximum amount of levels possible at the start of the UHC. Default: true
moduleInfiniteEnchanting: "true"

#Should sheep drop string when they die. Default: true
moduleSheepDropString: "true"

#Should gravel drop arrows when broken. Default: true
moduleGravelDropArrow: "true"

#Should we block tools crafted with the Enchanted Tools module from being used in a grindstone
moduleDissalowGrindingEnchantedTools: "true"

#Do we allow the crafting of light golden apples
moduleLightGoldenApple: "true"

#Do we allow the crafting of light anvils
moduleLightAnvil: "true"

moduleProximityVoice: "true"