name: UHCPlus
main: nl.thedutchmc.uhcplus.UhcPlus
version: 1.0.0
author: [TheDutchMC, TimeMaster111]
api-version: 1.15
description: TBD
depend: [WorldEdit]
commands:
 uhcp:
  description: uhcp base command. See /uhcp help for help.
 chat:
  description: toggle between team chat and global chat
 discord:
  description: Allows the user to add their discord name to their minecraft profile