name: UHCPlus
main: nl.thedutchmc.uhcplus.UhcPlus
version: @version@
author: TheDutchMC
api-version: 1.16
description: A highly configurable UHC Plugin
website: https://github.com/TheDutchMC/uhcplus
depend: [WorldEdit]
commands:
 uhcp:
  description: uhcp base command. See /uhcp help for help.
 chat:
  description: toggle between team chat and global chat
 broadcast:
  description: Broadcast a message to all online players.
 teaminventory:
  description: Opens team inventory for the executor's team
  aliases: ti
 coords:
  description: Put your coordinates into Team Chat
  aliases: c
 revive:
  description: Revive a team member
  aliases: r
permissions:
 uhcp.*:
  description: Grants access to all UHCPlus commands
  default: op
  children:
   uhcp.preset.*: true
   uhcp.teams.*: true
   uhcp.broadcast: true
   uhcp.chat: true
   uhcp.teaminventory: true
   uhcp.coords: true
   uhcp.gui.*: true
   uhcp.start: true
   uhcp.help: true
   uhcp.kits.*: true
   uhcp.revive: true
 uhcp.preset.*:
  description: Grants the player access to all /uhcp preset <arguments> commands
  default: op
  children:
   uhcp.preset.create: true
   uhcp.preset.delete: true
   uhcp.preset.list: true
   uhcp.preset.load: true
   uhcp.preset.options: true
   uhcp.preset.options: true
   uhcp.preset.seeloaded: true
   uhcp.preset.setdefault: true
   uhcp.preset.help: true
 uhcp.preset.create:
  description: Allows the player to create a new preset
  default: op
 uhcp.preset.delete:
  description: Allows the player to delete a preset
  default: op 
 uhcp.preset.list:
  description: Allows the player to list existing presets
  default: op
 uhcp.preset.load:
  description: Allows the player to load a preset
  default: op
 uhcp.preset.options:
  description: Allows the player to modify options for the loaded preset
  default: op
 uhcp.preset.seeloaded:
  description: Allows the player to see which preset is currently loaded
  default: op
 uhcp.preset.setdefault:
  description: Allows the player to set the default preset
  default: op
 uhcp.preset.help:
  description: Allows the user to access the preset help page
  default: op
 uhcp.teams.*:
  description: Grants the player access to all /uhcp teams <arguments> commands
  default: op
  children:
   uhcp.teams.getteams: true
   uhcp.teams.randomfill: true
   uhcp.teams.help: true
   uhcp.teams.whichteam: true
   uhcp.teams.jointeam: true
   uhcp.teams.teamcount: true
 uhcp.teams.getteams:
  description: Allows the user to list all the teams
  default: op
 uhcp.teams.randomfill:
  description: Allows the user to force resort the teams randomly
  default: op
 uhcp.teams.help:
  description: Allows the user to access the teams help page
  default: op
 uhcp.teams.whichteam:
  description: Allows the user to see in which team a player is
  default: op
 uhcp.teams.jointeam:
  description: Allows the user to join a team
  default: op
 uhcp.teams.teamcount:
  description: Shows the amount of teams configured
  default: op
 uhcp.broadcast:
  description: Allows the use of /broadcast
  default: op
 uhcp.chat:
  description: Allows the use of /chat
  default: true
 uhcp.teaminventory:
  description: Allows the use of /ti and /teaminventory
  default: true
 uhcp.coords:
  description: Allows the use of /c and /coords
  default: true
 uhcp.gui.*:
  description: Grans the player access to all GUIs
  default: op
  children:
   uhcp.gui.teams: true
   uhcp.gui.recipes: true
   uhcp.gui.modules: true
 uhcp.gui.teams:
  description: Allows the user to see and use the Teams gui
  default: true
 uhcp.gui.recipes:
  description: Allows the user to see and use the Recipes gui
  default: true
 uhcp.gui.modules:
  description: Allows the user to see and use the Modules gui
  default: op
 uhcp.start:
  description: Allows the user to start the uhc
  default: op
 uhcp.help:
  description: Allows the user to see the UHCPlus help page
  default: op
 uhcp.version:
  description: Allows the user to use the version command
  default: true
 uhcp.kits.*:
  description: Grants the user access to use all /uhcp kits commands
  default: op
  children:
   uhcp.kits.create: true
   uhcp.kits.modify: true
   uhcp.kits.list: true
   uhcp.kits.help: true
   uhcp.kits.remove: true
 uhcp.kits.create:
  description: Allows the user to use /uhcp kits create
  default: op
 uhcp.kits.modify:
  description: Allows the user to use /uhcp kits modify
  default: op
 uhcp.kits.list:
  description: Allows the user to use /uhcp kits list
  default: op
 uhcp.kits.help:
  description: Allows the user to use /uhcp kits help
  default: op
 uhcp.kits.remove:
  description: Allows the user to use /uhcp kits remove
  default: op
 uhcp.revive:
  description: Allows the user to use /revive even when they are not playing
  default: op
  
  
  
  
  
  
  
  
  
  
  
